Adding Data Dashboard link to Slow Zone posts
transitmatters/mbta-slow-zone-bot pull request #25
Opened 2023-05-16 01:36 UTC by nathan-weinberg

Fixes #15 

@skaplan-dev I was able to kinda test this by putting the function somewhere unconventional and doing a dry run of the bot, but curious if you have a way to test this stuff so I could visualize how it looks?

2023-05-17 12:55 UTC, skaplan-dev commented
> Fixes #15
> 
> @skaplan-dev I was able to kinda test this by putting the function somewhere unconventional and doing a dry run of the bot, but curious if you have a way to test this stuff so I could visualize how it looks?
> 
> @devinmatte not sure if there's anyway to future-proof this for V4, but if so feel free to advise 👍

no super great way to test this besides just printing things out locally. it might be worth us building a `test` Twitter bot for stuff like this.

2023-05-17 13:35 UTC, nathan-weinberg commented
> > Fixes #15
> > @skaplan-dev I was able to kinda test this by putting the function somewhere unconventional and doing a dry run of the bot, but curious if you have a way to test this stuff so I could visualize how it looks?
> > @devinmatte not sure if there's anyway to future-proof this for V4, but if so feel free to advise +1
> 
> no super great way to test this besides just printing things out locally. it might be worth us building a `test` Twitter bot for stuff like this. I'd actually prefer if we tweeted the dashboard link as a response to the tweet (open to debating this). We don't have great twitter `meta` tags that add nice visualizations for dashboard links.

I'd def be open to that idea - I think visually it'd be more appealing - we might need to play with the bot logic since the reply scheme would work differently for Mastodon/Slack.

Another thing I was looking into was URL shorteners  for the Dashboard links so they might look a bit better as part of the main tweet - we would probably need to sign up for a service like [Bitly](https://bitly.com/) for that, the only native Python library I could find for that [seems abandoned](https://github.com/ellisonleao/pyshorteners/).

2023-08-03 20:54 UTC, devinmatte commented
We should update this now with v4 links

2023-08-10 02:43 UTC, devinmatte requested changes

2023-08-10 02:43 UTC, devinmatte commented on utils.py
> +    link = f"https://dashboard.transitmatters.org/rapidtransit?config={color},{stop1},{stop2},{start},{end}"
Format for v4 is
```suggestion
    link = f"https://dashboard.transitmatters.org/{color}/trips/multi/
    ?from={stop1}&to={stop2}&startDate={start}&endDate={end}"
```

2023-08-17 02:35 UTC, devinmatte approved these changes
LGTM. Maybe wait on @skaplan-dev to make sure we're ready to launch this

2023-08-17 22:28 UTC, nathan-weinberg commented
I tried to test this with the test Twitter bot but was unable to do so - would someone who configured the Prod bot be able to adjust the settings to allow for write access? Can share the keys via Slack if needed

2023-08-17 22:28 UTC, nathan-weinberg commented
Ofc we can always merge this and hope for the best :smile:

2023-08-19 12:54 UTC, merged