feat: Support Bluesky
transitmatters/mbta-slow-zone-bot pull request #53
Opened 2024-11-20 18:30 UTC by kmackenzieii

*Ensure your PR title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec*

## Motivation

Bluesky is becoming more popular. Now is a good time to add a bot

See feature request ticket #46 

## Changes

added support for automated posting to Bluesky in the same style as other bots. 

added dependency on [AT Protocol SDK for Python](https://atproto.blue/en/latest/index.html)

See post from [test bot](https://bsky.app/profile/25d6f49a955b8b1d.bsky.social)

## Testing Instructions

Create an account on [Bluesky](https://bsky.app/).

Create an app password _optional_ 

Export the following environment variables
`ATP_PDS_HOST`=the url of the pds server if self hosting, will default to bluesky's server _optional_ 
`ATP_AUTH_HANDLE`=the handle for the account
`ATP_AUTH_PASSWORD`=the password or app password for the account

run as usual, i.e. `poetry run python3 slowzones.py`

2024-11-20 23:20 UTC, nathan-weinberg reviewed
Overall looking good to me! Couple comments

We'll get the creds added to the GitHub account before merging :+1:

2024-11-20 23:20 UTC, nathan-weinberg commented on README.md
> +A Twitter & Mastodon & Slack & Bluesky bot to track MBTA slow zones
It does it all!

2024-11-20 23:20 UTC, nathan-weinberg commented on slowzones.py
> +bluesky_client.login(login=ATP_AUTH_HANDLE, password=ATP_AUTH_PASSWORD)
This seems to be what's failing the dry run: https://github.com/transitmatters/mbta-slow-zone-bot/actions/runs/11939535356/job/33280264410?pr=53

Maybe this client login should be moved under L126 so it's captured by our existing exception?

If so we should follow suit with the other domains, but that can be a separate PR.

2024-11-25 21:37 UTC, devinmatte requested changes

2024-11-25 21:37 UTC, devinmatte commented on slowzones.py
> +ATP_PDS_HOST = os.environ.get("ATP_PDS_HOST") or None
This is not being defined for the CI, meaning dry run or otherwise can't run

2024-11-25 21:43 UTC, devinmatte approved these changes

2024-11-25 21:43 UTC, merged